create extension if not exists pgcrypto;

do $$
begin
	if not exists (select 1 from pg_type where typname = 'user_role') then
		create type public.user_role as enum ('user', 'admin');
	end if;

	if not exists (select 1 from pg_type where typname = 'issue_status') then
		create type public.issue_status as enum ('reported', 'in_review', 'resolved', 'rejected');
	end if;

	if not exists (select 1 from pg_type where typname = 'issue_severity') then
		create type public.issue_severity as enum ('low', 'medium', 'high', 'critical');
	end if;
end
$$;

create table if not exists public.profiles (
	id uuid primary key references auth.users (id) on delete cascade,
	full_name text,
	role public.user_role not null default 'user',
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.road_issues (
	id uuid primary key default gen_random_uuid(),
	reporter_id uuid not null references public.profiles (id) on delete restrict,
	title text not null check (char_length(title) between 5 and 140),
	description text not null check (char_length(description) between 10 and 2000),
	status public.issue_status not null default 'reported',
	severity public.issue_severity not null default 'medium',
	latitude numeric(9, 6) not null check (latitude between -90 and 90),
	longitude numeric(9, 6) not null check (longitude between -180 and 180),
	address text,
	image_path text not null,
	assigned_to uuid references public.profiles (id) on delete set null,
	admin_notes text,
	resolved_at timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table if not exists public.issue_updates (
	id bigint generated by default as identity primary key,
	issue_id uuid not null references public.road_issues (id) on delete cascade,
	updated_by uuid not null references public.profiles (id) on delete restrict,
	old_status public.issue_status,
	new_status public.issue_status,
	comment text,
	created_at timestamptz not null default now()
);

create index if not exists idx_road_issues_status on public.road_issues (status);
create index if not exists idx_road_issues_created_at on public.road_issues (created_at desc);
create index if not exists idx_road_issues_severity on public.road_issues (severity);
create index if not exists idx_road_issues_lat_lng on public.road_issues (latitude, longitude);
create index if not exists idx_issue_updates_issue_id on public.issue_updates (issue_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
	select exists (
		select 1
		from public.profiles p
		where p.id = auth.uid() and p.role = 'admin'
	);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
	insert into public.profiles (id, full_name)
	values (
		new.id,
		coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
	)
	on conflict (id) do nothing;

	return new;
end;
$$;

create or replace function public.log_issue_status_change()
returns trigger
language plpgsql
as $$
begin
	if new.status is distinct from old.status then
		insert into public.issue_updates (issue_id, updated_by, old_status, new_status, comment)
		values (new.id, auth.uid(), old.status, new.status, new.admin_notes);

		if new.status = 'resolved' and old.status is distinct from 'resolved' then
			new.resolved_at = now();
		end if;
	end if;

	return new;
end;
$$;

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_road_issues_set_updated_at on public.road_issues;
create trigger trg_road_issues_set_updated_at
before update on public.road_issues
for each row
execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

drop trigger if exists trg_road_issue_status_change on public.road_issues;
create trigger trg_road_issue_status_change
before update on public.road_issues
for each row
execute function public.log_issue_status_change();

alter table public.profiles enable row level security;
alter table public.road_issues enable row level security;
alter table public.issue_updates enable row level security;

drop policy if exists "Users can read own profile or admin can read all" on public.profiles;
create policy "Users can read own profile or admin can read all"
on public.profiles
for select
to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (
	auth.uid() = id
	and role = (select p.role from public.profiles p where p.id = auth.uid())
);

drop policy if exists "Admins can update any profile" on public.profiles;
create policy "Admins can update any profile"
on public.profiles
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Authenticated users can read issues" on public.road_issues;
create policy "Authenticated users can read issues"
on public.road_issues
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can report issues" on public.road_issues;
create policy "Authenticated users can report issues"
on public.road_issues
for insert
to authenticated
with check (auth.uid() = reporter_id);

drop policy if exists "Admins can update issues" on public.road_issues;
create policy "Admins can update issues"
on public.road_issues
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete issues" on public.road_issues;
create policy "Admins can delete issues"
on public.road_issues
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Authenticated users can read issue updates" on public.issue_updates;
create policy "Authenticated users can read issue updates"
on public.issue_updates
for select
to authenticated
using (true);

drop policy if exists "Admins can write issue updates" on public.issue_updates;
create policy "Admins can write issue updates"
on public.issue_updates
for insert
to authenticated
with check (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
	'road-issue-images',
	'road-issue-images',
	false,
	5242880,
	array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
	public = excluded.public,
	file_size_limit = excluded.file_size_limit,
	allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Authenticated users can upload issue images" on storage.objects;
create policy "Authenticated users can upload issue images"
on storage.objects
for insert
to authenticated
with check (
	bucket_id = 'road-issue-images'
	and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Authenticated users can read issue images" on storage.objects;
create policy "Authenticated users can read issue images"
on storage.objects
for select
to authenticated
using (bucket_id = 'road-issue-images');

drop policy if exists "Admins can update issue images" on storage.objects;
create policy "Admins can update issue images"
on storage.objects
for update
to authenticated
using (bucket_id = 'road-issue-images' and public.is_admin())
with check (bucket_id = 'road-issue-images' and public.is_admin());

drop policy if exists "Admins can delete issue images" on storage.objects;
create policy "Admins can delete issue images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'road-issue-images' and public.is_admin());

create or replace view public.issue_public_feed
with (security_invoker = true)
as
select
	ri.id,
	ri.title,
	ri.description,
	ri.status,
	ri.severity,
	ri.latitude,
	ri.longitude,
	ri.address,
	ri.image_path,
	ri.created_at,
	p.full_name as reporter_name
from public.road_issues ri
join public.profiles p on p.id = ri.reporter_id;

create or replace function public.admin_issue_dashboard()
returns table (
	total_issues bigint,
	reported_issues bigint,
	in_review_issues bigint,
	resolved_issues bigint,
	rejected_issues bigint,
	critical_issues bigint,
	issues_last_7_days bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
	if not public.is_admin() then
		raise exception 'admin privileges required';
	end if;

	return query
	select
		count(*) as total_issues,
		count(*) filter (where status = 'reported') as reported_issues,
		count(*) filter (where status = 'in_review') as in_review_issues,
		count(*) filter (where status = 'resolved') as resolved_issues,
		count(*) filter (where status = 'rejected') as rejected_issues,
		count(*) filter (where severity = 'critical') as critical_issues,
		count(*) filter (where created_at >= now() - interval '7 day') as issues_last_7_days
	from public.road_issues;
end;
$$;

create or replace function public.nearby_open_issues(
	p_latitude double precision,
	p_longitude double precision,
	p_radius_km double precision default 5
)
returns table (
	id uuid,
	title text,
	description text,
	status public.issue_status,
	severity public.issue_severity,
	latitude numeric,
	longitude numeric,
	address text,
	image_path text,
	created_at timestamptz,
	distance_km double precision
)
language sql
stable
as $$
	select
		ri.id,
		ri.title,
		ri.description,
		ri.status,
		ri.severity,
		ri.latitude,
		ri.longitude,
		ri.address,
		ri.image_path,
		ri.created_at,
		(
			6371 * acos(
				least(
					1,
					greatest(
						-1,
						cos(radians(p_latitude))
						* cos(radians(ri.latitude::double precision))
						* cos(radians(ri.longitude::double precision) - radians(p_longitude))
						+ sin(radians(p_latitude)) * sin(radians(ri.latitude::double precision))
					)
				)
			)
		) as distance_km
	from public.road_issues ri
	where ri.status in ('reported', 'in_review')
	and (
		6371 * acos(
			least(
				1,
				greatest(
					-1,
					cos(radians(p_latitude))
					* cos(radians(ri.latitude::double precision))
					* cos(radians(ri.longitude::double precision) - radians(p_longitude))
					+ sin(radians(p_latitude)) * sin(radians(ri.latitude::double precision))
				)
			)
		)
	) <= p_radius_km
	order by distance_km asc;
$$;

grant usage on schema public to authenticated;

grant select, update on public.profiles to authenticated;
grant select, insert on public.road_issues to authenticated;
grant select on public.issue_updates to authenticated;
grant select on public.issue_public_feed to authenticated;

grant execute on function public.admin_issue_dashboard() to authenticated;
grant execute on function public.nearby_open_issues(double precision, double precision, double precision) to authenticated;
